# -*- coding: utf-8 -*-
"""Seaborn_and_Linear_Regression_(start).ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1KYXQrn37CzHVYaFYYBlRSEJobv0x113q

# Introduction

Do higher film budgets lead to more box office revenue? Let's find out if there's a relationship using the movie budgets and financial performance data that I've scraped from [the-numbers.com](https://www.the-numbers.com/movie/budgets) on **May 1st, 2018**. 

<img src=https://i.imgur.com/kq7hrEh.png>

# Import Statements
"""

import pandas as pd
import matplotlib.pyplot as plt
import numpy as np
import seaborn as sns
from sklearn.linear_model import LinearRegression

"""# Notebook Presentation"""

pd.options.display.float_format = '{:,.2f}'.format

from pandas.plotting import register_matplotlib_converters
register_matplotlib_converters()

"""# Read the Data"""

data = pd.read_csv('cost_revenue_dirty.csv')

"""# Explore and Clean the Data

**Challenge**: Answer these questions about the dataset:
1. How many rows and columns does the dataset contain?
2. Are there any NaN values present?
3. Are there any duplicate rows?
4. What are the data types of the columns?
"""

data.shape

data.columns

print(data.isna().values.any())
print("-----------------------------------")
print(data.isnull().values.any())
print("-----------------------------------")
print(data.isna().values.sum())

print(data.duplicated().sum())
print(data.duplicated().values.any())

data.info()

data.dtypes

"""### Data Type Conversions

**Challenge**: Convert the `USD_Production_Budget`, `USD_Worldwide_Gross`, and `USD_Domestic_Gross` columns to a numeric format by removing `$` signs and `,`. 
<br>
<br>
Note that *domestic* in this context refers to the United States.
"""

data.head(15)

data.USD_Production_Budget = data.USD_Production_Budget.astype(str).str.replace("$", "").str.replace(",", "")
data.USD_Production_Budget = pd.to_numeric(data.USD_Production_Budget)
data.USD_Worldwide_Gross = data.USD_Worldwide_Gross.astype(str).str.replace("$", "").str.replace(",", "")
data.USD_Worldwide_Gross = pd.to_numeric(data.USD_Worldwide_Gross)
data.USD_Domestic_Gross = data.USD_Domestic_Gross.astype(str).str.replace("$", "").str.replace(",", "")
data.USD_Domestic_Gross = pd.to_numeric(data.USD_Domestic_Gross)
print(data.dtypes)
print("------------------------------------")
data.head(15)

chars_to_remove = ["$", ","]
columns_to_convert = ["USD_Production_Budget", "USD_Worldwide_Gross", "USD_Domestic_Gross"]
for column in columns_to_convert:
  for char in chars_to_remove:
    data[column] = data[column].astype(str).str.replace(char, "")
  data[column] = pd.to_numeric(data[column])

data.sample(15)

"""**Challenge**: Convert the `Release_Date` column to a Pandas Datetime type. """

data.Release_Date = pd.to_datetime(data.Release_Date)
print(data.dtypes)
print("------------------------------------")
data.head(15)

"""### Descriptive Statistics

**Challenge**: 

1. What is the average production budget of the films in the data set?
2. What is the average worldwide gross revenue of films?
3. What were the minimums for worldwide and domestic revenue?
4. Are the bottom 25% of films actually profitable or do they lose money?
5. What are the highest production budget and highest worldwide gross revenue of any film?
6. How much revenue did the lowest and highest budget films make?
"""

data.describe()

data[data.USD_Production_Budget == 1100]

data[data.USD_Production_Budget == 425000000]

data.USD_Production_Budget.mean()

data.USD_Worldwide_Gross.mean()

print(data.USD_Domestic_Gross.min())
print(data.USD_Worldwide_Gross.min())

zeros_domestic = data[data["USD_Domestic_Gross"] == 0]
print(zeros_domestic.shape)
print(f"Number of films with no domestic revenue: {len(zeros_domestic)}")
zeros_domestic.sort_values("USD_Production_Budget", ascending=False)

zeros_worldwide = data[data["USD_Worldwide_Gross"] == 0]
print(zeros_worldwide.shape)
print(f"Number of films with no worldwide revenue: {len(zeros_worldwide)}")
zeros_worldwide.sort_values("USD_Production_Budget", ascending=False)

"""# Investigating the Zero Revenue Films

**Challenge** How many films grossed $0 domestically (i.e., in the United States)? What were the highest budget films that grossed nothing?
"""

zeros_domestic = data[data["USD_Domestic_Gross"] == 0]
print(zeros_domestic.shape)
print(f"Number of films with no domestic revenue: {len(zeros_domestic)}")
zeros_domestic.sort_values("USD_Production_Budget", ascending=False)

"""**Challenge**: How many films grossed $0 worldwide? What are the highest budget films that had no revenue internationally?"""

zeros_worldwide = data[data["USD_Worldwide_Gross"] == 0]
print(zeros_worldwide.shape)
print(f"Number of films with no worldwide revenue: {len(zeros_worldwide)}")
zeros_worldwide.sort_values("USD_Production_Budget", ascending=False)

"""### Filtering on Multiple Conditions"""

international_releases = data.loc[(data.USD_Worldwide_Gross != 0) & (data.USD_Domestic_Gross == 0)]
print(f"Number of films released international: {len(international_releases)}")
international_releases

"""**Challenge**: Use the [`.query()` function](https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.DataFrame.query.html) to accomplish the same thing. Create a subset for international releases that had some worldwide gross revenue, but made zero revenue in the United States. 

Hint: This time you'll have to use the `and` keyword.
"""

bool_list1 = [True, True, False, False]
bool_list2 = [False, True, True, False]
np.array(bool_list1) & np.array(bool_list2)

international_releases2 = data.query("USD_Worldwide_Gross != 0 & USD_Domestic_Gross == 0")
print(f"Number of international releases: {len(international_releases2)}")
international_releases2

"""### Unreleased Films

**Challenge**:
* Identify which films were not released yet as of the time of data collection (May 1st, 2018).
* How many films are included in the dataset that have not yet had a chance to be screened in the box office? 
* Create another DataFrame called data_clean that does not include these films. 
"""

# Date of Data Collection
scrape_date = pd.Timestamp('2018-5-1')
unreleased_films = data[data.Release_Date >= scrape_date]
print(f"Number of unreleased films: {len(unreleased_films)}")
unreleased_films

scrape_date = pd.Timestamp('2018-5-1')
unreleased_films2 = data.loc[data.Release_Date >= scrape_date]
print(f"Unreleased films: {len(unreleased_films2)}")
unreleased_films2

data_clean = data.drop(unreleased_films.index)
print(data_clean.shape)
print(f"{len(data) - len(data_clean)}")

"""### Films that Lost Money

**Challenge**: 
What is the percentage of films where the production costs exceeded the worldwide gross revenue? 
"""

over_budget_films = data_clean[data_clean.USD_Production_Budget > data_clean.USD_Worldwide_Gross]
print(f"Number of films that lost money: {len(over_budget_films)}")
over_budget_films.sample(20)

over_budget_films2 = data_clean.loc[data_clean.USD_Production_Budget > data_clean.USD_Worldwide_Gross]
print(f"Number of films that lost money: {len(over_budget_films2)}")
over_budget_films2.sample(5)

over_budget_films3 = data_clean.query("USD_Production_Budget > USD_Worldwide_Gross")
print(f"Number of films that lost money: {len(over_budget_films3)}")
over_budget_films2.sample(5)

percent = len(over_budget_films) / len(data_clean) * 100
print(percent)
print(f"Films that lost money from dataset: {'{:,.2f}'.format(percent)} percent")

print(f"Films that lost money from dataset: {'{:,.2f}'.format(over_budget_films3.shape[0] / data_clean.shape[0] * 100)} %")

"""# Seaborn for Data Viz: Bubble Charts"""

sns.scatterplot(data = data_clean,
                x = "USD_Production_Budget",
                y = "USD_Worldwide_Gross")

plt.figure(figsize=(8, 4), dpi=200)

sns.scatterplot(data = data_clean,
                x = "USD_Production_Budget",
                y = "USD_Worldwide_Gross")

plt.show()

plt.figure(figsize=(8, 4), dpi=200)

ax = sns.scatterplot(data = data_clean,
                x = "USD_Production_Budget",
                y = "USD_Worldwide_Gross")

ax.set(ylim = (0, 3000000000),
       xlim = (0, 450000000),
       ylabel = "Revenue in $ billions",
       xlabel = "Budget in $100 millions")

plt.show()

plt.figure(figsize=(8, 4), dpi=200)

ax = sns.scatterplot(data = data_clean,
                x = "USD_Production_Budget",
                y = "USD_Worldwide_Gross",
                hue = "USD_Worldwide_Gross",
                size = "USD_Worldwide_Gross")

ax.set(ylim = (0, 3000000000),
       xlim = (0, 450000000),
       ylabel = "Revenue in $ billions",
       xlabel = "Budget in $100 millions")

plt.show()

plt.figure(figsize=(8, 4), dpi=200)

with sns.axes_style("darkgrid"):
  ax = sns.scatterplot(data = data_clean,
                  x = "USD_Production_Budget",
                  y = "USD_Worldwide_Gross",
                  hue = "USD_Worldwide_Gross",
                  size = "USD_Worldwide_Gross")

  ax.set(ylim = (0, 3000000000),
        xlim = (0, 450000000),
        ylabel = "Revenue in $ billions",
        xlabel = "Budget in $100 millions")

plt.figure(figsize=(8, 4), dpi=200)

with sns.axes_style("ticks"):
  ax = sns.scatterplot(data = data_clean,
                  x = "USD_Production_Budget",
                  y = "USD_Worldwide_Gross",
                  hue = "USD_Worldwide_Gross",
                  size = "USD_Worldwide_Gross")

  ax.set(ylim = (0, 3000000000),
        xlim = (0, 450000000),
        ylabel = "Revenue in $ billions",
        xlabel = "Budget in $100 millions")

"""### Plotting Movie Releases over Time

**Challenge**: Try to create the following Bubble Chart:

<img src=https://i.imgur.com/8fUn9T6.png>


"""

data_clean.sort_values("Release_Date", ascending=True)

plt.figure(figsize=(8, 4), dpi=200)

with sns.axes_style("darkgrid"):
  ax = sns.scatterplot(data = data_clean,
                  x = "Release_Date",
                  y = "USD_Worldwide_Gross",
                  hue = "USD_Worldwide_Gross",
                  size = "USD_Worldwide_Gross")

  ax.set(ylim = (0, 3000000000),
         xlim = (pd.Timestamp("1915-8-1"), pd.Timestamp("2018-5-1")),
         ylabel = "Revenue in $ billions",
         xlabel = "Release Year")

plt.figure(figsize=(8, 4), dpi=200)

with sns.axes_style("darkgrid"):
  ax = sns.scatterplot(data = data_clean,
                  x = "Release_Date",
                  y = "USD_Worldwide_Gross",
                  hue = "USD_Worldwide_Gross",
                  size = "USD_Worldwide_Gross")

  ax.set(ylim = (0, 3000000000),
         xlim = (data_clean.Release_Date.min(), data_clean.Release_Date.max()),
         ylabel = "Revenue in $ billions",
         xlabel = "Release Year")

"""# Converting Years to Decades Trick

**Challenge**: Create a column in `data_clean` that has the decade of the release. 

<img src=https://i.imgur.com/0VEfagw.png width=650> 

Here's how: 
1. Create a [`DatetimeIndex` object](https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.DatetimeIndex.html) from the Release_Date column. 
2. Grab all the years from the `DatetimeIndex` object using the `.year` property.
<img src=https://i.imgur.com/5m06Ach.png width=650>
3. Use floor division `//` to convert the year data to the decades of the films.
4. Add the decades as a `Decade` column to the `data_clean` DataFrame.
"""

datetime_index = pd.Series([index.year for index in data_clean.Release_Date])
datetime_index

datetime_index2 = pd.DatetimeIndex(data_clean.Release_Date)
print(datetime_index2)
print("-----------------------------------------------")
datetime_index_year_only = datetime_index2.year
datetime_index_year_only

decade = (datetime_index_year_only // 10) * 10
decade

data_clean["Decade"] = decade
data_clean

"""### Separate the "old" (before 1969) and "New" (1970s onwards) Films

**Challenge**: Create two new DataFrames: `old_films` and `new_films`
* `old_films` should include all the films before 1969 (up to and including 1969)
* `new_films` should include all the films from 1970 onwards
* How many films were released prior to 1970?
* What was the most expensive film made prior to 1970?
"""

old_films = data_clean.loc[data_clean.Decade < 1970]
print(f"Number of films released before 1970: {len(old_films)}")
print(f"Most expensive films released before 1970 is {old_films.iloc[old_films.USD_Production_Budget.idxmax()].Movie_Title} with ${'{:,.2f}'.format(old_films.USD_Production_Budget.max())} budget.")
old_films

new_films = data_clean.loc[data_clean.Decade >= 1970]
print(f"Number of films released 1970 and up: {len(new_films)}")
print(f"Most expensive films released from 1970 and up is {new_films.iloc[new_films.USD_Production_Budget.idxmax()].Movie_Title} with ${'{:,.2f}'.format(new_films.USD_Production_Budget.max())} budget.")
new_films

"""# Seaborn Regression Plots"""

sns.regplot(data = old_films,
            x = "USD_Production_Budget",
            y = "USD_Worldwide_Gross")

plt.figure(figsize=(8, 4), dpi=200)
with sns.axes_style("whitegrid"):
  sns.regplot(data = old_films,
            x = "USD_Production_Budget",
            y = "USD_Worldwide_Gross",
            scatter_kws = {"alpha": 0.4},
            line_kws = {"color": "black"})

"""**Challenge**: Use Seaborn's `.regplot()` to show the scatter plot and linear regression line against the `new_films`. 
<br>
<br>
Style the chart

* Put the chart on a `'darkgrid'`.
* Set limits on the axes so that they don't show negative values.
* Label the axes on the plot "Revenue in \$ billions" and "Budget in \$ millions".
* Provide HEX colour codes for the plot and the regression line. Make the dots dark blue (#2f4b7c) and the line orange (#ff7c43).

Interpret the chart

* Do our data points for the new films align better or worse with the linear regression than for our older films?
* Roughly how much would a film with a budget of $150 million make according to the regression line?
"""

plt.figure(figsize=(8, 4), dpi=200)
with sns.axes_style("darkgrid"):
  ax = sns.regplot(data = new_films,
              x = "USD_Production_Budget",
              y = "USD_Worldwide_Gross",
              scatter_kws = {"color": "#2f4b7c", "alpha": 0.6},
              line_kws = {"color": "#ff7c43"})
  
  ax.set(
      ylim = (new_films.USD_Worldwide_Gross.min(), 3000000000),
      xlim = (new_films.USD_Production_Budget.min(), 450000000),
      # ylim = (new_films.USD_Worldwide_Gross.min(), new_films.USD_Worldwide_Gross.max()),
      # xlim = (new_films.USD_Production_Budget.min(), new_films.USD_Production_Budget.max()),
      ylabel = "Revenue in $ billions",
      xlabel = "Budget in $ millions"
      )

"""# Run Your Own Regression with scikit-learn

$$ REV \hat ENUE = \theta _0 + \theta _1 BUDGET$$
"""

regression = LinearRegression()

# Explanatory Variable(s) or Feature(s)
X = pd.DataFrame(new_films, columns=['USD_Production_Budget'])
 
# Response Variable or Target
y = pd.DataFrame(new_films, columns=['USD_Worldwide_Gross'])

"""Our `LinearRegression` does not like receiving Pandas Series (e.g., `new_films.USD_Production_Budget`), so I've created some new DataFrames here"""

# Find the best-fit line
regression.fit(X, y)

# Theta zero
regression.intercept_

# Theta one
regression.coef_

# R-squared
regression.score(X, y)

"""**Challenge**: Run a linear regression for the `old_films`. Calculate the intercept, slope and r-squared. How much of the variance in movie revenue does the linear model explain in this case?"""

regression_old = LinearRegression()

# Explanatory Variable(s) or Feature(s)
X_old = pd.DataFrame(old_films, columns=['USD_Production_Budget'])
 
# Response Variable or Target
y_old = pd.DataFrame(old_films, columns=['USD_Worldwide_Gross'])

# Find the best-fit line
regression_old.fit(X_old, y_old)

# Theta zero
regression_old.intercept_
print(f"The intercept is: {'{:,.2f}'.format(regression_old.intercept_[0])}")

# Theta one
regression_old.coef_
print(f"The slope coefficient is: {'{:,.2f}'.format(regression_old.coef_[0][0])}")

# R-squared
regression_old.score(X_old, y_old)
print(f"The r-squared is : {'{:,.2f}'.format((regression_old.score(X_old, y_old) * 100))} %")

"""# Use Your Model to Make a Prediction

We just estimated the slope and intercept! Remember that our Linear Model has the following form:

$$ REV \hat ENUE = \theta _0 + \theta _1 BUDGET$$

**Challenge**:  How much global revenue does our model estimate for a film with a budget of $350 million? 
"""

# revenue using the new_films model
# revenue = theta_zero + theta_one * budget
revenue_model_new_films = regression.intercept_[0] + regression.coef_[0][0] * 350000000
print(f"The estimated revenue for $350 millions budget film using new_films model is : {'{:,.2f}'.format(revenue_model_new_films)}")

# revenue using the old_films model
# revenue = theta_zero + theta_one * budget
revenue_model_old_films = regression_old.intercept_[0] + regression_old.coef_[0][0] * 350000000
print(f"The estimated revenue for $350 millions budget film using old_films model is : {'{:,.2f}'.format(revenue_model_old_films)}")