print("Welcome to the tip calculator.")
total_bill = float(input("What was the total bill? $"))
split_by = int(input("How many people to split the bill? "))
tip_percent = int(input("What percentage tip would you like to give? 10, 12, or 15? "))
per_person_pay = round(total_bill * ((100 + tip_percent) / 100) / split_by, 2)
print(f"Each person should pay : ${per_person_pay}")
